inc_file_path: "/tmp/vagrant-puppet/files" # Absolute path to the puppet template files directory (No need to change it)
tz: "America/Lima" # Timezone
user: "USER" # User to create
password: "PASSWORD" # The user's password
project: "PROJECT_NAME" # Django project folder or the name when you run django-admin.py startproject <PROJECT_NAME>
domain_name: "DOMAIN_NAME.com" # Used in apache, uwsgi and virtualenv directory
hostname: "HOSTNAME" # Used in Vagrantfile
db_name: "DB_NAME" # Mysql database name to create
db_user: "DB_USER" # Mysql username to create
db_password: "DB_PASSWORD" # Mysql password for the db_user
connection:
  use: 'office'
  home:
    public_ip: '192.168.0.211'
    interface: 'en0: Wi-Fi (AirPort)'
  office:
    public_ip: '192.168.0.244'
    interface: 'eth0'